/*
 * Automatically generated by Magic
 */
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { TranslateModule } from '@ngx-translate/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MaterialModule } from './material.module';
import { NgxImageCompressService } from 'ngx-image-compress';
import { A11yModule } from '@angular/cdk/a11y';

import { CoreModule } from '@core';
import { SharedModule } from '@shared';
import { AuthModule } from '@app/auth';
import { HomeModule } from './home/home.module';
import { ShellModule } from './shell/shell.module';
import { AppComponent } from './app.component';
import { MagicSelectorComponent } from './helpers/magic-selector/magic-selector.component';
import { MagicUsernameLookupComponent } from './helpers/magic-username-lookup/magic-username-lookup.component';
import { MagicAutocompleteComponent } from './helpers/magic-autocomplete/magic-autocomplete.component';
import { MagicFilterComponent } from './helpers/magic-filter/magic-filter.component';
import { MagicImageComponent } from './helpers/magic-image/magic-image.component';
import { MagicImageFieldComponent } from './helpers/magic-image-field/magic-image-field.component';
import { MagicImageViewComponent } from './helpers/magic-image-view/magic-image-view.component';
import { MagicFileViewComponent } from './helpers/magic-file-view/magic-file-view.component';
import { MagicFileComponent } from './helpers/magic-file/magic-file.component';
import { MagicFileFieldComponent } from './helpers/magic-file-field/magic-file-field.component';
import { AppRoutingModule } from './app-routing.module';
import { environment } from '@env/environment';
import { JwtModule } from '@auth0/angular-jwt';
import { OwlDateTimeModule, OwlNativeDateTimeModule } from '@danielmoncada/angular-datetime-picker';
import { FormatDatePipe } from './pipes/format-date-pipe';
import { DateSincePipe } from './pipes/date-since.pipe';
import { ConfirmDialogComponent } from './confirm-deletion-dialog/confirm-dialog.component';
import { UserManagementComponent } from './common/user-management/user-management.component';
import { EditUserDialogComponent } from './common/user-management/edit-user-dialog/edit-user-dialog.component';
import { CreateUserDialogComponent } from './common/user-management/create-user-dialog/create-user-dialog.component';
import { EditExtraFieldsComponent } from './common/user-management/edit-extra-fields/edit-extra-fields.component';

// Generated CRUD components here.
import { Chinook_AlbumComponent } from './components/chinook/Album/chinook_Album.component';
import { EditChinook_AlbumComponent } from './components/chinook/Album/modals/edit.chinook_Album.component';
import { Chinook_ArtistComponent } from './components/chinook/Artist/chinook_Artist.component';
import { EditChinook_ArtistComponent } from './components/chinook/Artist/modals/edit.chinook_Artist.component';
import { Chinook_CustomerComponent } from './components/chinook/Customer/chinook_Customer.component';
import { EditChinook_CustomerComponent } from './components/chinook/Customer/modals/edit.chinook_Customer.component';
import { Chinook_EmployeeComponent } from './components/chinook/Employee/chinook_Employee.component';
import { EditChinook_EmployeeComponent } from './components/chinook/Employee/modals/edit.chinook_Employee.component';
import { Chinook_GenreComponent } from './components/chinook/Genre/chinook_Genre.component';
import { EditChinook_GenreComponent } from './components/chinook/Genre/modals/edit.chinook_Genre.component';
import { Chinook_InvoiceComponent } from './components/chinook/Invoice/chinook_Invoice.component';
import { EditChinook_InvoiceComponent } from './components/chinook/Invoice/modals/edit.chinook_Invoice.component';
import { Chinook_InvoiceLineComponent } from './components/chinook/InvoiceLine/chinook_InvoiceLine.component';
import { EditChinook_InvoiceLineComponent } from './components/chinook/InvoiceLine/modals/edit.chinook_InvoiceLine.component';
import { Chinook_MediaTypeComponent } from './components/chinook/MediaType/chinook_MediaType.component';
import { EditChinook_MediaTypeComponent } from './components/chinook/MediaType/modals/edit.chinook_MediaType.component';
import { Chinook_PlaylistComponent } from './components/chinook/Playlist/chinook_Playlist.component';
import { EditChinook_PlaylistComponent } from './components/chinook/Playlist/modals/edit.chinook_Playlist.component';
import { Chinook_PlaylistTrackComponent } from './components/chinook/PlaylistTrack/chinook_PlaylistTrack.component';
import { EditChinook_PlaylistTrackComponent } from './components/chinook/PlaylistTrack/modals/edit.chinook_PlaylistTrack.component';
import { Chinook_TrackComponent } from './components/chinook/Track/chinook_Track.component';
import { EditChinook_TrackComponent } from './components/chinook/Track/modals/edit.chinook_Track.component';


@NgModule({
  imports: [
    OwlDateTimeModule,
    OwlNativeDateTimeModule,
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    TranslateModule.forRoot(),
    BrowserAnimationsModule,
    MaterialModule,
    CoreModule,
    SharedModule,
    ShellModule,
    HomeModule,
    AuthModule,
    JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          const persisted = sessionStorage.getItem('credentials') || localStorage.getItem('credentials');
          if (persisted) {
            return JSON.parse(persisted).token;
          }
          return null;
        },
        allowedDomains: [environment.apiDomain],
      },
    }),
    AppRoutingModule, // must be imported as the last module as it contains the fallback route
    A11yModule
  ],
  declarations: [
    AppComponent,
    MagicSelectorComponent,
    MagicUsernameLookupComponent,
    MagicAutocompleteComponent,
    MagicFilterComponent,
    MagicImageComponent,
    MagicImageFieldComponent,
    MagicImageViewComponent,
    MagicFileViewComponent,
    MagicFileComponent,
    MagicFileFieldComponent,
    FormatDatePipe,
    DateSincePipe,
    ConfirmDialogComponent,
    UserManagementComponent,
    EditUserDialogComponent,
    CreateUserDialogComponent,
    EditExtraFieldsComponent,

    // Generated CRUD components here.
    Chinook_AlbumComponent,
    EditChinook_AlbumComponent,
    Chinook_ArtistComponent,
    EditChinook_ArtistComponent,
    Chinook_CustomerComponent,
    EditChinook_CustomerComponent,
    Chinook_EmployeeComponent,
    EditChinook_EmployeeComponent,
    Chinook_GenreComponent,
    EditChinook_GenreComponent,
    Chinook_InvoiceComponent,
    EditChinook_InvoiceComponent,
    Chinook_InvoiceLineComponent,
    EditChinook_InvoiceLineComponent,
    Chinook_MediaTypeComponent,
    EditChinook_MediaTypeComponent,
    Chinook_PlaylistComponent,
    EditChinook_PlaylistComponent,
    Chinook_PlaylistTrackComponent,
    EditChinook_PlaylistTrackComponent,
    Chinook_TrackComponent,
    EditChinook_TrackComponent,
  ],

  providers: [NgxImageCompressService],
  bootstrap: [AppComponent],
})
export class AppModule {}
