/*
 * Automatically generated by Magic
 */

// Angular specific components
import { throwError } from 'rxjs';
import { Component, OnInit, ViewChild } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { GridComponent } from '@app/base/grid.component';
import { MatPaginator } from '@angular/material/paginator';
import { MatDialog } from '@angular/material/dialog';
import { FormControl } from '@angular/forms';
import { DomSanitizer } from '@angular/platform-browser';
import {
  trigger,
  state,
  style,
  transition,
  animate
} from '@angular/animations';

// Application specific components
import { EditChinook_CustomerComponent } from './modals/edit.chinook_Customer.component';
import { HttpService } from 'src/app/services/http-service';
import { AuthService } from 'src/app/services/auth-service';

/**
 * "Datagrid" component for displaying instance of Customer
 * entities from your HTTP REST backend.
 */
@Component({
  selector: 'app-chinook_Customer',
  templateUrl: './chinook_Customer.component.html',
  styleUrls: ['./chinook_Customer.component.scss'],
  animations: [
    trigger('detailExpand', [
      state('collapsed', style({height: '0px', opacity: '0'})),
      state('expanded', style({height: '*', opacity: '1'})),
      transition('expanded <=> collapsed', animate('0.75s cubic-bezier(0.4, 0.0, 0.2, 1)')),
    ])
  ]
})
export class Chinook_CustomerComponent extends GridComponent implements OnInit {

  /**
   * Which columns we should display. Reorder to prioritize columns differently.
   * Notice! 'delete-instance' should always come last.
   */
  public displayedColumns: string[] = [
    'FirstName',
    'LastName',
    'SupportRepId.LastName',
    'Company',
    'Address',
    'City',
    'State',
    'Country',
    'PostalCode',
    'Phone',
    'Fax',
    'Email',
    'delete-instance'
  ];

  /**
   * What element is currently expanded.
   */
  public expandedElement: any | null;


  // Need to view paginator as a child to update page index of it.
  @ViewChild(MatPaginator, {static: true}) paginator: MatPaginator;

  // Form control declarations to bind up with reactive form elements.
  public FirstName: FormControl;
  public LastName: FormControl;
  public SupportRepId_LastName: FormControl;
  public Company: FormControl;
  public Address: FormControl;
  public City: FormControl;
  public State: FormControl;
  public Country: FormControl;
  public PostalCode: FormControl;
  public Phone: FormControl;
  public Fax: FormControl;
  public Email: FormControl;
  public CustomerId: FormControl;
  public SupportRepId: FormControl;


  /**
   * Creates an instance of your CRUD component.
   * 
   * @param httpService Needed to be able to invoke backend during CRUD operations
   * @param authService Needed to check if user has access to invoking CRUD operation
   * @param snackBar Needed to display errror and feedback
   * @param dialog Needed to show modal dialog as user edits or creates new entities
   * @param sanitizer Needed to be able to dynamically display iframes
   */
   constructor(
    public httpService: HttpService,
    public authService: AuthService,
    protected snackBar: MatSnackBar,
    protected dialog: MatDialog,
    protected sanitizer: DomSanitizer) {
      super(authService, snackBar, dialog, sanitizer);
  }

  /**
   * Overridde abstract method necessary to return the URL endpoint
   * for CRUD methods to base class.
   */
  public entityBaseUrl() {
    return 'magic/modules/chinook/Customer';
  }

  /**
   * Overridden abstract method from base class, that returns the Observable
   * necessary to actually retrieve items from backend.
   */
  protected read(filter: any) {
    return this.httpService.chinook_Customer.read(filter);
  }

  /**
   * Overridden abstract method from base class, that returns the Observable
   * necessary to actually retrieve count of items from backend.
   */
  protected count(filter: any) {
    return this.httpService.chinook_Customer.count(filter);
  }

  /**
   * Overridden abstract method from base class, that returns the Observable
   * necessary to actually delete items in backend.
   */
  protected delete(ids: any) {
    return this.httpService.chinook_Customer.delete(ids);
  }

  /**
   * Implementation of abstract base class method, to reset paginator
   * of component.
   */
  protected resetPaginator() {
    this.paginator.pageIndex = 0;
    this.filter.offset = 0;
  }

  /**
   * OnInit implementation. Retrieves initial data (unfiltered),
   * and instantiates our FormControls.
   */
  public ngOnInit() {

    // Retrieves data from our backend, unfiltered, and binds our mat-table accordingly.
    this.getData();

    /*
     * Creating our filtering FormControl instances, which gives us "live filtering"
     * on our columns.
     */
    this.FirstName = this.createFormControl('Customer.FirstName.like');
    this.LastName = this.createFormControl('SupportRepId.LastName.like');
    this.SupportRepId_LastName = this.createFormControl('SupportRepId.LastName.like');
    this.Company = this.createFormControl('Customer.Company.like');
    this.Address = this.createFormControl('Customer.Address.like');
    this.City = this.createFormControl('Customer.City.like');
    this.State = this.createFormControl('Customer.State.like');
    this.Country = this.createFormControl('Customer.Country.like');
    this.PostalCode = this.createFormControl('Customer.PostalCode.like');
    this.Phone = this.createFormControl('Customer.Phone.like');
    this.Fax = this.createFormControl('Customer.Fax.like');
    this.Email = this.createFormControl('Customer.Email.like');
    this.CustomerId = this.createFormControl('Customer.CustomerId.eq');
    this.SupportRepId = this.createFormControl('Customer.SupportRepId.eq');
  }

  /**
   * Invoked when user wants to edit an entity
   * 
   * This will show a modal dialog, allowing the user to edit his record.
   */
  public editEntity(entity: any) {

    const dialogRef = this.dialog.open(EditChinook_CustomerComponent, {
      data: this.getEditData(entity)
    });
    dialogRef.afterClosed().subscribe(res => {
      if (res) {
        this.setEditData(res, entity);
      }
    });
  }

  /**
   * Invoked when user wants to create a new entity
   * 
   * This will show a modal dialog, allowing the user to supply
   * the initial data for the entity.
   */
  public createEntity() {

    const dialogRef = this.dialog.open(EditChinook_CustomerComponent, {
      data: {
        isEdit: false,
        entity: {},
      }});
    dialogRef.afterClosed().subscribe((res: any) => {
      if (res) {
        this.itemCreated(res);
      }
    });
  }
}
