/*
 * Automatically generated by Magic
 */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { marker } from '@biesbjerg/ngx-translate-extract-marker';

import { HomeComponent } from './home.component';
import { Shell } from '@app/shell/shell.service';
import { UserManagementComponent } from '@app/common/user-management/user-management.component';

// Then importing all CRUD components.
import { Chinook_AlbumComponent } from '../components/chinook/Album/chinook_Album.component';
import { Chinook_ArtistComponent } from '../components/chinook/Artist/chinook_Artist.component';
import { Chinook_CustomerComponent } from '../components/chinook/Customer/chinook_Customer.component';
import { Chinook_EmployeeComponent } from '../components/chinook/Employee/chinook_Employee.component';
import { Chinook_GenreComponent } from '../components/chinook/Genre/chinook_Genre.component';
import { Chinook_InvoiceComponent } from '../components/chinook/Invoice/chinook_Invoice.component';
import { Chinook_InvoiceLineComponent } from '../components/chinook/InvoiceLine/chinook_InvoiceLine.component';
import { Chinook_MediaTypeComponent } from '../components/chinook/MediaType/chinook_MediaType.component';
import { Chinook_PlaylistComponent } from '../components/chinook/Playlist/chinook_Playlist.component';
import { Chinook_PlaylistTrackComponent } from '../components/chinook/PlaylistTrack/chinook_PlaylistTrack.component';
import { Chinook_TrackComponent } from '../components/chinook/Track/chinook_Track.component';


const routes: Routes = [
  Shell.childRoutes([
    { path: '', component: HomeComponent, data: { title: marker('Home') } },
    { path: 'users', component: UserManagementComponent, data: { title: marker('User management') } },

    // Then routes for all CRUD components.
    { path: 'crud/chinook/Album', component: Chinook_AlbumComponent, data: { title: marker('chinook/Album') } },
    { path: 'crud/chinook/Artist', component: Chinook_ArtistComponent, data: { title: marker('chinook/Artist') } },
    { path: 'crud/chinook/Customer', component: Chinook_CustomerComponent, data: { title: marker('chinook/Customer') } },
    { path: 'crud/chinook/Employee', component: Chinook_EmployeeComponent, data: { title: marker('chinook/Employee') } },
    { path: 'crud/chinook/Genre', component: Chinook_GenreComponent, data: { title: marker('chinook/Genre') } },
    { path: 'crud/chinook/Invoice', component: Chinook_InvoiceComponent, data: { title: marker('chinook/Invoice') } },
    { path: 'crud/chinook/InvoiceLine', component: Chinook_InvoiceLineComponent, data: { title: marker('chinook/InvoiceLine') } },
    { path: 'crud/chinook/MediaType', component: Chinook_MediaTypeComponent, data: { title: marker('chinook/MediaType') } },
    { path: 'crud/chinook/Playlist', component: Chinook_PlaylistComponent, data: { title: marker('chinook/Playlist') } },
    { path: 'crud/chinook/PlaylistTrack', component: Chinook_PlaylistTrackComponent, data: { title: marker('chinook/PlaylistTrack') } },
    { path: 'crud/chinook/Track', component: Chinook_TrackComponent, data: { title: marker('chinook/Track') } },

  ]),
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
  providers: [],
})
export class HomeRoutingModule {}
